# Забираем шаблоны
include:
  - '/gitlab-ci/template.yml'

# Ставим переменные дочернего пайплайна
variables:
  PROJECT: "HTTP/AuthService" # <-- PROJECT: "(Название сервиса)"
  DOCKERNAME: "bomes-http-auth" # <-- DOCKERNAME: "(Имя контейнера)"

# jobs внутри дочернего пайплайна
BomesAPI_build:  # <-- (Название сервиса)_build
  extends: .build-template-servises
