apiVersion: apps/v1
kind: Deployment
metadata:
    name: bomes-http-core
spec:
    replicas: 2
    selector:
        matchLabels:
            app: bomes-http-core
    template:
        metadata:
            labels:
                app: bomes-http-core
        spec:
            containers:
                - name: bomes-http-core
                  image: bomes-hub:5000/bomes-http-core:latest
                  env:
                      - name: TZ
                        value: Europe/Moscow
                      - name: RabbitMQ_host
                        value: rabbitmq
                      - name: RabbitMQ_port
                        value: 5672
---
apiVersion: v1
kind: Service
metadata:
    name: bomes-http-core-service
spec:
    selector:
        app: bomes-http-core
    ports:
        - port: 3000
          targetPort: 3000
