apiVersion: apps/v1
kind: Deployment
metadata:
    name: bomes-ws-core
spec:
    replicas: 2
    selector:
        matchLabels:
            app: bomes-ws-core
    template:
        metadata:
            labels:
                app: bomes-ws-core
        spec:
            containers:
                - name: bomes-ws-core
                  image: bomes-hub:5000/bomes-ws-core:latest
                  ports:
                      - containerPort: 8000
                  env:
                      - name: TZ
                        value: Europe/Moscow
---
apiVersion: v1
kind: Service
metadata:
    name: bomes-ws-core-service
spec:
    selector:
        app: bomes-ws-core
    ports:
        - port: 8000
          targetPort: 8000
